# Generated by Django 4.2.5 on 2023-10-13 20:02

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.IntegerField(primary_key=builtins.id, serialize=False),
        ),
    ]
